config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :institutions, only: [:show, :index]
  resources :objects, only: [:show, :index], controller: 'things'
  resources :prints, only: [:index, :show]
  resources :boxes, only: [:index, :show]
  resources :boops, only: [:index, :create]

  root 'pages#home'
 
  get '/boxes/:id/list' => 'boxes#list'
 
  get '/about' => 'pages#about'
  get '/sowhat' => 'pages#sowhat'
  get '/help' => 'pages#help'
  get '/contact' => 'pages#contact'
  get '/thebrain' => 'pages#thebrain'
  get '/discussion' => 'pages#discussion'
  
  
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :description_attribution_url, presence: true

  belongs_to :institution

  belongs_to :collection

  has_many :links

  has_many :prints

  has_many :media
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  def show
    @thing = Thing.find(params[:id])
    @prints = @thing.prints.includes(:box)
    if admin_user_signed_in? || !@thing.collection.private
      render
    else
      not_found
    end
  end

  def index
    if admin_user_signed_in?
      @things = Thing.all().order(:id)
    else
      # Remove any private collections
      @things = Thing.joins(:collection).where("collections.private" => false).order(:id)
    end
  end

end

app/views/things/index.html.erb
<h1>Objects</h1>

<ol>
<% @things.each do |thing| %>
  <li><%= link_to thing.name, object_path(thing) %></li>
<% end %>
</ol>

app/views/things/show.html.erb
<p><a href="/objects">Objects</a></p>
<h1><%= @thing.name %></h1>

<div class="row">
	<div class="twelve columns">
		<p><a href="<%= @thing.image %>" style="text-decoration:none;"><img src="<%= @thing.image %>" alt="<%= @thing.image_alt_text %>" style="width:100%;"></a></p>
	</div>
</div>

<div class="row">
	<div class="seven columns">
		<p class="lead">
			<%= @thing.description %>
		</p>
		<p><a href="<%= @thing.description_attribution_url %>">Source of description</a>
		<% if @thing.wikipedia_url.present? %>
		 + <a href="<%= @thing.wikipedia_url %>">Wikipedia</a>
		 <% end %>
		 </p>
 		<p>The original is a <%= @thing.three_dimensions ? '3D' : '2D' %> object.</p>
                <% unless @thing.media.empty? %>
                  <% @thing.media.each do |medium| %>
                  <div>
                    <% if medium.media_type == 1 %>
                      <img src="<%= medium.link_or_embed %>">
                      <% if medium.attribution %>
                      <p><%= medium.attribution %></p>
                      <% end %>
                    <% else %>
                      <%= raw(medium.link_or_embed) %>
                    <% end %>
                  </div>
                  <% end %>
                <% end %>
                <% unless @thing.links.empty? %>
                <h5>Links</h5>
                <ul>
                  <% @thing.links.each do |link| %>
                  <li><a href="<%= link.url %>"><%= link.description %></a></li>
                  <% end %>
                </ul>
                <% end %>
	</div>
	<div class="three columns">

		<h5>From</h5>
	<% if @thing.institution %>
	  <p><%= link_to @thing.institution.name, @thing.institution %></p>
	<% else %>
	  <p>This object didn't come from an institution.</p>
	<% end %>
	
		<h5>Made by</h5>
		<p>
		  <% @thing.creators.each do |creator| %>
			<span><%= creator %></span>
		  <% end %>
		</p>
		
		<h5>Tags</h5>	
		<p class="tag">
		  <% @thing.tags.each do |tag| %>
			<span><%= tag %></span>
		  <% end %>
		</p>	
	
	</div>	
	<div class="two columns">
		<h5>Prints</h5>
		<p>
			[image of any prints, link to print view]
		</p>

		<h5>Boxes</h5>
		<p>
		<% @prints.each do |print| %>
			<%= link_to "Box #{print.box.id}", box_path(print.box) %>
		<% end %>
		</p>	
	</div>
	
</div>

<h3>Prints</h3>
<table width="100%">
	<tr>
		<th>Print ID</th>
		<th>Box</th>
		<th>Created</th>
		<th>Sent To</th>
		<th>Last Boop</th>
	</tr>
	<% @prints.each do |print| %>
		<tr>
			<td><%= link_to print.id, print_path(print) %></td>
			<td><%= link_to "Box #{print.box.id}", box_path(print.box) %></td>
			<td><%= time_ago_in_words(print.created_at) %> ago</td>
			<td></td>
			<td></td>
		</tr>
	<% end %>
</table>