config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :institutions, only: [:show, :index]
  resources :objects, only: [:show, :index], controller: 'things'
  resources :prints, only: [:index, :show]
  resources :boxes, only: [:index, :show]
  resources :boops, only: [:index, :create]

  root 'pages#home'
 
  get '/boxes/:id/list' => 'boxes#list'
 
  get '/about' => 'pages#about'
  get '/sowhat' => 'pages#sowhat'
  get '/help' => 'pages#help'
  get '/contact' => 'pages#contact'
  get '/thebrain' => 'pages#thebrain'
  get '/discussion' => 'pages#discussion'
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Museum in a Box</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<!-- start nav -->
		<div class="row nav">
	  	<div class="one column logo" title="Museum in a Box!">
				<a href="/"><img src="/museuminabox-logo-black.svg" width="60" /></a>
		  </div>
	    <div class="eleven columns">
				<ul>
				  <li><%= current_link_to "Home", "/" %></li>
				  <li><%= current_link_to "Museums", institutions_path, "institutions" %></li>
				  <li><%= current_link_to "Objects", objects_path, "things" %></li>
				  <li><%= current_link_to "Boxes", boxes_path, "boxes" %></li>
		     	          <li><%= current_link_to "So What?", "/sowhat" %></li>
				  <li><%= current_link_to "Help", "/help" %></li>
                                <% if admin_user_signed_in? -%>
                                  <li><%= current_link_to "Admin", "/admin" -%></li>
                                <% end -%>
				</ul>
	    </div>      
	  </div>
		<!-- end nav -->    
	    
		<%= yield %>

		<!-- start foot -->
		<hr />
		<div class="row foot">
			<div class="two columns"><a href="#top">&uarr; Top</a></div>
			<div class="three columns offset-by-one">		
				<ul>
					<li><a href="/institutions">Museums</a></li>
					<li><a href="/objects">Objects</a></li>
					<li>
						<a href="/boxes">Boxes</a> 
						&
						<a href="/thebrain">The Brain</a>
					</li>
					<li><a href="/boops">Boops</a></li>
				</ul>
			</div>
			<div class="three columns">		
				<ul>
					<li><a href="/about">About Us</a></li>
					<li><a href="/contact">Contact</a></li>
					<li><a href="/discussion">Discussion</a></li>
				</ul>
			</div>
			<div class="three columns">		
				<p><small>Museum in a Box Ltd. is registered in England. Company Number: 09849074.</small></p>
			</div>
		</div>
	<!-- end foot -->
	</div>
</body>
</html>